[program:dtc-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/dtc-dashboard/artisan queue:work redis --sleep=3 --tries=3 --timeout=60
autostart=true
autorestart=true
stopwaitsecs=3600
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dtc-queue-worker.log
user=www-data
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",HOME="/var/www/dtc-dashboard",LARAVEL_TINKER_WITHOUT_PAYER=true
