name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: [ubuntu-latest]

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, tokenizer, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          tools: composer

      - name: Copy .env.ci to .env
        run: cp .env.ci .env

      - name: Install composer dependencies
        run: composer install --no-scripts --no-interaction --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up database configuration
        run: |
          php artisan config:cache
          php artisan migrate --force

      - name: Run tests
        run: vendor/bin/phpunit
