name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: [ubuntu-latest]
    # container:
    #   image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    # steps:
    #   - uses: actions/checkout@v1
    #     with:
    #       fetch-depth: 1

    #   - name: Install composer dependencies
    #     run: composer install --no-scripts

    #   - name: Install npm dependencies
    #     run: npm install

    #   - name: Run Vite
    #     run: npm run build

    #   - name: Prepare Laravel Application
    #     run: cp .env.ci .env

    #   - name: Generate application key
    #     run: php artisan key:generate

    #   - name: Run Testsuite
    #     run: php artisan test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, tokenizer, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          tools: composer

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Set up database configuration
        run: |
          php artisan config:cache
          php artisan migrate --force

      - name: Run tests
        run: vendor/bin/phpunit
